config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts do
    resources :comments
  end

  get :about , controller: :pages
  get :profile, controller: :pages
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def new
    @comment = @post.comments.new(comment_params)
    @comment.save
  end

  def create
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js   {}
        # format.json { render json: @comment, status: :created, location: @post }
      else
        format.html { render action: "new" }
        # format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
  end

  def show
  end

  def index
    @comments = @post.comments.all
  end

  private
  
  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @name = "首頁"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @name = "首頁"
    @posts = Post.all
  end

  def new
    @name = "新增文章"
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save

    redirect_to :action => :index
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments
    @contents = @post.comments.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :content,:author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li class="collection-item avatar">
  <%= image_tag 'profile.jpg', class:'circle' %>
  <span class="title"><%= comment.name %></span>
  <p>
    <%= comment.body %>
  </p>
  <%= link_to '刪除', [comment.post, comment],
                  method: :delete,
                  class: "secondary-content",
                   data: { confirm: 'Are you sure?' } %>
</li>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], :remote => true) do |f| %>
	<%= f.label :name,'名稱' %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :body,'內容' %><br>
	<%= f.text_area :body, class: 'materialize-textarea' %><br>
	<br>
	<%= f.submit '送出', class: 'btn',id: 'comment-button' %>
<% end %>

app/views/comments/create.js.erb
$(".comments_place")
    .append($("<%= escape_javascript(render @comment) %>"));

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
<li class="collection-item avatar">
  <%= image_tag 'profile.jpg', class:'circle' %>
  <span class="title"><%= comment.name %></span>
  <p>
    <%= comment.body %>
  </p>
  <%= link_to '刪除', [comment.post, comment],
                  method: :delete,
                  class: "secondary-content",
                   data: { confirm: 'Are you sure?' } %>
</li>
<% end %>

app/views/comments/show.html.erb
<div class="comment-area" id="comment-area">
  <h5>目前有<%= @post.comments.count %> 則回應</h5>
  <ul class="collection clearfix" id="comment-area">
    <%= render @post.comments %>
  </ul>
  <br> <br>
  <%= render 'comments/form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sudo-Blog <%= @name %></title>
  <link rel="stylesheet" href="layout.css">
  <link rel="stylesheet" href="materialize.css">
  <script src="materialize.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="fullpage clearfix">
  <header class="kai-header">
      <nav>
          <div class="nav-wrapper">
              <a href="/" class="brand-logo center logo-box"><span>Sudo-blog</span></a>
              <ul class="right hide-on-small-only">
                  <li><%= link_to '首頁', root_path %></li>
                  <li><%= link_to '關於', about_path %></a></li>
                  <li><%= link_to '新增文章', new_post_path %></li>
              </ul>
              <ul class="left">
                  <li>
                      <a href="#" id="open-menu" class="btn bg-color cmn-toggle-switch cmn-toggle-switch__htla active hide-on-large-only">
                          <span>toggle menu</span>
                      </a>
                  </li>
              </ul>

          </div>
      </nav>
  </header>
  <div class="l-menu hide-on-small-only z-depth-2">
      <div id="1" class="user-info">
          <div class="user-info-img">
              <a href=""><%= image_tag 'profile.jpg' %></a>
          </div>
      </div>
      <ul class="l-menu-content">
          <li><a href="<%= root_path %>">文章列表</a></li>
          <li><a href="articlelist.html">收藏文章</a></li>
      </ul>
      <ul class="l-menu-content">
          <li><%= link_to '關於sudo', about_path %></li>
          <li><%= link_to '個人檔案', profile_path %></li>
      </ul>
  </div>
  <div class="main-container">
    <div class="container">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="image-bar">
  <%= image_tag 'sudo.jpg' %>
</div>

<p>
  以 Linux 最高權限指令為名，Sudo Recruit 提供給使用者的是最高規格的求職媒合服務，團隊於2012年加入 Appworks 加速器計畫後 (台灣最興盛的網路創業加速器)，就致力於協助軟體工程師找到最適合的舞台。
</p>

app/views/pages/index.html.erb
<h2>hello,blog</h2>

app/views/pages/profile.html.erb
<div class="row">
    <div class="col s12 m12 l12 center">
        <div class="heading"><span class="title">實習生檔案</span></div>
        <div class="profile-container col s12 m10 l10 offset-l1 offset-m1">
            <table class="striped">
                <tbody>
                  <tr>
                    <td>姓名</td>
                    <td>陳愷奕</td>
                  </tr>
                  <tr>
                      <td>生日</td>
                      <td>1994/11/11</td>
                  </tr>
                  <tr>
                    <td>學校科系</td>
                    <td>台灣科技大學-資訊管理系</td>
                  </tr>
                  <tr>
                    <td>興趣與專長</td>
                    <td>
                        <li>專長：我很帥哦，這是我的專長，就是帥帥帥帥帥死你</li>
                        <li>興趣：平常喜歡彈鋼琴和朋友打屁聊天</li>
                    </td>
                  </tr>
                  <tr>
                      <td>職業</td>
                      <td>
                          <p>我目前還是一位在台北努力生存的大學生哦！對社會上、職場上的問題都還不熟悉。</p>
                      </td>
                  </tr>
                  <tr>
                      <td>最近的困擾</td>
                      <td>
                        <p>一直以來我的困擾就是太帥了，女生看到我都會主動貼上來，害我都不知道怎麼辦了才好。如果你有好方法的話，還請你教教我</p>
                      </td>
                  </tr>
                  <tr>
                      <td>夢想、未來目標</td>
                      <td>
                          <p>
                              未來希望能夠到世界各地旅行，成為舉世聞名的帥哥。
                          </p>
                      </td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <%= form_for @post, :url => {:controller => 'posts', :action => 'update'} do |f| %>
    <div class="col s12 m12 l12">
      <div class="row">
        <%= f.label :title, "文章名稱" %>
        <%= f.text_field :title, id: "input-field",class:"col s12 m12 l12" %>
      </div>
      <div class="row">
        <%= f.label :author, "作者" %>
        <%= f.text_field :author, id: "author-field", class:"col s6 m12 l12" %>
      </div>

      <div class="row">
        <%= f.label :content, "文章內容" %>
        <%= f.text_area :content, id: "textarea1",class: "materialize-textarea" %>
      </div>
    </div>
    <%= f.submit "送出", class:"btn" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="row">
  <% @posts.each do |post| %>
    <div class="col s12 m6 l4">
      <a href="<%= post_path(post) %>">
        <div class="article-card  card-panel">
            <div class="article-card-img"><%= image_tag 'profile.jpg' %></div>
            <div class="article-card-title"><h5> <%= post.title %></h5></div>
            <div class="article-card-content"><%= post.content %></div>
            <div class="article-card-author"><span><%= post.author %></span></div>
        </div>
      </a>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <%= form_for @post, :url => {:controller => 'posts', :action => 'create'} do |f| %>
    <div class="col s12 m12 l12">
      <div class="row">
        <%= f.label :title, "文章名稱" %>
        <%= f.text_field :title, id: "input-field" %>
        <%= f.label :author, "作者" %>
        <%= f.text_field :author, id: "input-field" %>
      </div>
      <div class="row">
        <%= f.label :content, "文章內容" %>
        <%= f.text_area :content, id: "textarea1",class: "materialize-textarea" %>
      </div>
    </div>
    <%= f.submit "送出", class:"btn" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="article col s12 m12 l9">
    <div class="article-heading">
      <h4><%= @post.title %></h4>
      <%= link_to '修改文章', edit_post_path %>
    </div>
    <div class="article-content">
      <%= simple_format(@post.content) %>
    </div>
  </div>
</div>

<div class="row">
     <div class="col s12 m12 l12">
         <div class="author-box clearfix">
             <div class="author-box-img"><%= image_tag 'profile.jpg' %></div>
             <div class="author-box-intro">
                 <span class="title">作者介紹-<%= @post.author %></span>

                 <p>棲息地在圖書館。喜歡亂寫東西，把自己腦袋中的想法用文字表達出來。 為了不讓時間淡泊回憶創了一個小部落格。寫點日記文、小說心得文、社會感想文、民生議題文來說些什麼。 從一位平凡大學生的觀點看世界。 重度文字控ｘ網路成癮患者ｘ專業啃小說ｘ偽文青。 </p>
             </div>
        </div>
     </div>
</div>

<!-- <div id="comment-area" class="comment-area">
  <h5>目前有<%= @post.comments.count %> 則回應</h5>
  <ul class="collection clearfix" id="comment-area">
    <%= render @post.comments %>
  </ul>
  <br> <br>
  
</div> -->
<div id="comment-area" class="comment-area">
  <h5>目前有<%= @post.comments.count %> 則回應</h5>
  <ul class="collection clearfix comments_place" id="comment-area">
    <%= render @post.comments %>
  </ul>
  <br> <br>
  
</div>
<%= render 'comments/form' %>
<script type="text/javascript">

</script>

app/views/posts/show.js.erb
$('#comment-area ul').html('
fuck bug
');